config/routes.rb
Rails.application.routes.draw do

  get 'access_permissions/new'
  get 'access_permissions/edit'
  get 'access_permissions/index'
  get 'access_permissions/show'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get   '/controls', to: 'controls#home'
  get   '/action',   to: 'controls#action'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :rpis
  resources :devices
  resources :access_controls
  resources :access_control_doors
  resources :access_permissions
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/access_control.rb
class AccessControl < ApplicationRecord
  has_many :access_permissions, dependent: :destroy
  has_many :access_control_doors, :through => :access_permissions
  before_save :downcase_badge_holder_email
  validates :key_code, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :badge_holder_email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates_format_of :badge_holder_phone, :with => /\(?[0-9]{3}\)?\s[0-9]{3}-[0-9]{4}/,
  :message => "- Phone numbers must be in (xxx) xxx-xxxx format."

  private

    # Converts email to all lower-case.
    def downcase_badge_holder_email
      self.badge_holder_email = badge_holder_email.downcase
    end

end

app/controllers/access_controls_controller.rb
class AccessControlsController < ApplicationController
  before_action :auth_user, only: [:index, :show]
  before_action :auth_admin, only: [:index, :show, :new, :create,
                                   :edit, :update, :destroy]

  def index
    @access_controls = AccessControl.all.paginate(page: params[:page])
    @access_controls_view = AccessControl.all
  end

  def show
    @access_control = AccessControl.find(params[:id])
  end

  def new
    @access_control = AccessControl.new
  end

  def create
    @access_control = AccessControl.new(access_control_params)
    if @access_control.save
      flash[:info] = "Successfully added Prox Badge"
      redirect_to access_controls_path
    else
      render 'new'
    end
  end

  def edit
    @access_control = AccessControl.find(params[:id])
  end

  def update
    @access_control = AccessControl.find(params[:id])
    if @access_control.update_attributes(access_control_params)
      flash[:success] = "Badge updated"
      redirect_to access_control_path
    else
      render 'edit'
    end
  end

  def destroy
    AccessControl.find(params[:id]).destroy
    flash[:success] = "Prox Badge deleted"
    redirect_to access_controls_path
  end

  private

  def access_control_params
    params.require(:access_control).
      permit(:user_first_name, :user_last_name, :description, :office_number,
             :badge_holder_phone, :badge_holder_email, :key_code, :access_level)
  end

  #confirms a logged in user.
  def auth_user
    if !current_user
      redirect_to root_url
    end
  end

  # Confirms an admin user.
  def auth_admin
    if !current_user.admin
      redirect_back
    end
  end
end

app/helpers/access_controls_helper.rb
module AccessControlsHelper
end

app/views/access_controls/edit.html.erb
<% provide(:title, "Edit "+@access_control.key_code) %>
<div class="row content-justify-center">
  <div class="col-sm-3">
  </div>
  <div class="col-md-5 shadow p-3 mb-5 bg-white rounded">
    <div class="card text-center">
      <div class="card-header text-white bg-primary text-center">
        <h4>Edit <%= @access_control.key_code %></h4>
      </div>
      <div class="card-body text-center">
        <%= simple_form_for(@access_control, html: { class: 'form-inline' }) do |f| %>
        <table class="card-table table">
          <tr>
            <td class="text-left">
              <%= render 'shared/error_messages', object: f.object %>
              <%= f.label :user_first_name, "First name", style: 'display: block;' %>
              <%= f.input :user_first_name, label: false, error: 'First Name Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :user_last_name, "Last name", style: 'display: block;' %>
              <%= f.input :user_last_name, label: false, error: 'Last Name Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :description, "Badge Description", style: 'display: block;' %>
              <%= f.input :description, label: false, error: 'Badge Description Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :office_number, "Badge Holder Office Number", style: 'display: block;' %>
              <%= f.input :office_number, label: false%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :badge_holder_phone, "Badge Holder Phone Number", style: 'display: block;' %>
              <%= f.input :badge_holder_phone, label: false, error: 'Badge Holder Phone Number Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :badge_holder_email, "Badge Holder Email", style: 'display: block;' %>
              <%= f.input :badge_holder_email, label: false, error: 'Badge Holder Email Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :key_code, "Prox Card Code", style: 'display: block;' %>
              <%= f.input :key_code, label: false, error: 'Code Required' %>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :access_level, "Access Priveleges", style: 'display: block;' %>
              <%= f.input(:access_level, label: false, collection: ["Full", "Limited", "Temp"], :prompt => false) %>
            </td>
          </tr>
        </table>
        <br><br>
        <%= f.submit "Update Proximity Card", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>

app/views/access_controls/index.html.erb
<% provide(:title, "Prox Badges") %>
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-md-6 shadow p-3 mb-5 bg-white rounded">
    <div class="card text-center">
      <div class="card-header text-white bg-primary text-center">
        <h4><%= link_to(add_icon, new_access_control_path) %>&nbsp;&nbsp;Prox Badges</h4>
      </div>
      <div class="card-body text-center">
        <table class="card-table table">
          <tr>
            <th class="text-left">
            </th>
            <th class="text-center">
              ID:
            </th>
            <th class="text-center">
              Name:
            </th>
            <th class="text-center">
              Access Level:
            </th>
            <th class="text-center">
              Access Code:
            </th>
          </tr>
          <% @access_controls.order(:id).each  do |access| %>
            <tr>
              <td class="text-left">
              <% if admin_priv? %>
              <%= link_to(delete_icon, access_control_path(access.id), method: :delete, data: { confirm: "You sure?" }) %>
              <% end %>
              </td>
              <td class="text-center">
                <%= link_to("#{access.id}", access_control_path(access.id)) %>
              </td>
              <td class="text-center">
                <%= access.user_first_name %>&nbsp;<%= access.user_last_name %>
              </td>
              <td class="text-center">
                <%= access.access_level %>
              </td>
              <td class="text-center">
                <%= access.key_code %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="col-sm">
      </div>
    </div>
  </div>
</div>
<div class="row content-justify-center">
  <div class="col-sm">
  <br><br><br><br>
  </div>
</div>

app/views/access_controls/new.html.erb
<% provide(:title, "Add Key Card") %>
<div class="row content-justify-center">
  <div class="col-sm-3">
  </div>
  <div class="col-md-5 shadow p-3 mb-5 bg-white rounded">
    <div class="card text-center">
      <div class="card-header text-white bg-primary text-center">
        <h4>Add Device</h4>
      </div>
      <div class="card-body text-center">
        <%= simple_form_for(@access_control, html: { class: 'form-inline' }) do |f| %>
        <table class="card-table table">
          <tr>
            <td class="text-left">
              <%= render 'shared/error_messages', object: f.object %>
              <%= f.label :user_first_name, "First name", style: 'display: block;' %>
              <%= f.input :user_first_name, label: false, error: 'First Name Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :user_last_name, "Last name", style: 'display: block;' %>
              <%= f.input :user_last_name, label: false, error: 'Last Name Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :description, "Badge Description", style: 'display: block;' %>
              <%= f.input :description, label: false, error: 'Badge Description Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :office_number, "Badge Holder Office Number", style: 'display: block;' %>
              <%= f.input :office_number, label: false%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :badge_holder_phone, "Badge Holder Phone Number", style: 'display: block;' %>
              <%= f.input :badge_holder_phone, label: false, error: 'Badge Holder Phone Number Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :badge_holder_email, "Badge Holder Email", style: 'display: block;' %>
              <%= f.input :badge_holder_email, label: false, error: 'Badge Holder Email Required'%>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :key_code, "Prox Card Code", style: 'display: block;' %>
              <%= f.input :key_code, label: false, error: 'Code Required' %>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :access_level, "Access Priveleges", style: 'display: block;' %>
              <%= f.input(:access_level, label: false, collection: ["Full", "Limited", "Temp"], :prompt => true) %>
            </td>
          </tr>
        </table>
        <br><br>
        <%= f.submit "Add Proximity Card", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>

app/views/access_controls/show.html.erb
<% provide(:title, @access_control.key_code) %>
<div class="row content-justify-center">
  <div class="col-sm-3">
  </div>
  <div class="col-md-5 shadow p-3 mb-5 bg-white rounded">
    <div class="card text-center">
      <div class="card-header text-white bg-primary text-center">
        <h4><%= link_to(edit_icon, edit_access_control_path) %>&nbsp;&nbsp;<%= @access_control.key_code %></h4>
      </div>
      <div class="card-body text-center">
        <table class="card-table table">
          <tr>
            <td class="text-left">
              First Name:<br>
              <input type="text" class="form-control form-control-lg" value="<%= @access_control.user_first_name %>">
            </td>
          </tr>
          <tr>
            <td class="text-left">
              Last Name:<br>
              <input type="text" class="form-control form-control-lg" value="<%= @access_control.user_last_name %>">
            </td>
          </tr>
          <tr>
            <td class="text-left">
              Card Description:<br>
              <input type="text" class="form-control form-control-lg" value="<%= @access_control.description %>">
            </td>
          </tr>
          <tr>
            <td class="text-left">
              Office Number:<br>
              <input type="text" class="form-control form-control-lg" value="<%= @access_control.office_number %>">
            </td>
          </tr>
          <tr>
            <td class="text-left">
              Phone Number:<br>
              <input type="text" class="form-control form-control-lg" value="<%= @access_control.badge_holder_phone %>">
            </td>
          </tr>
          <tr>
            <td class="text-left">
              Email Address:<br>
              <input type="text" class="form-control form-control-lg" value="<%= @access_control.badge_holder_email %>">
            </td>
          </tr>
          <tr>
            <td class="text-left">
              Badge Key Code:<br>
              <input type="text" class="form-control form-control-lg" value="<%= @access_control.key_code %>">
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <div class="form_group">
                <label for="access_level">Access Level:</label>
                <input type:"text" class="form-control form-control-lg" id="access_level" value="<%= @access_control.access_level %>">
              </div>
            </td>
          </tr>
        </table>
        <br><br>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>