config/routes.rb
Rails.application.routes.draw do

  get 'access_permissions/new'
  get 'access_permissions/edit'
  get 'access_permissions/index'
  get 'access_permissions/show'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get   '/controls', to: 'controls#home'
  get   '/action',   to: 'controls#action'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :rpis
  resources :devices
  resources :access_controls
  resources :access_control_doors
  resources :access_permissions
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/rpi.rb
# frozen_string_literal: true

class Rpi < ApplicationRecord
  has_many :devices, dependent: :destroy
  require 'resolv'
  validates :rpi_name, presence: true, length: { maximum: 30 }, uniqueness: { case_sensitive: false }
  validates :rpi_ip, presence: true, :format => { :with => Resolv::IPv4::Regex }
end

app/controllers/rpis_controller.rb
# frozen_string_literal: true

class RpisController < ApplicationController
  before_action :auth_user, only: [:index, :show]
  before_action :auth_admin, only: [:index, :show, :new, :create,
                                   :edit, :update, :destroy]

  def index
    @rpis = Rpi.all.paginate(page: params[:page])
  end

  def show
    @rpi = Rpi.find(params[:id])
    @devices = Device.where(rpi_id: @rpi)
  end

  def new
    @rpi = Rpi.new
  end

  def create
    @rpi = Rpi.new(rpi_params)
    if @rpi.save
      flash[:info] = "Successfully added RPI"
      redirect_to rpis_path
    else
      render 'new'
    end
  end

  def edit
    @rpi = Rpi.find(params[:id])
  end

  def update
    @rpi = Rpi.find(params[:id])
    if @rpi.update_attributes(rpi_params)
      flash[:success] = "RPI updated"
      redirect_to rpi_path
    else
      render 'edit'
    end
  end

  def destroy
    Rpi.find(params[:id]).destroy
    flash[:success] = "RPI deleted"
    redirect_to rpis_path
  end

  private

  def rpi_params
    params.require(:rpi).permit(:rpi_name, :rpi_location, :rpi_ip, :rpi_model)
  end

  #confirms a logged in user.
  def auth_user
    if !current_user
      redirect_to root_url
    end
  end

  # Confirms an admin user.
  def auth_admin
    if !current_user.admin
      redirect_back
    end
  end
end

app/helpers/rpis_helper.rb
module RpisHelper

  def rpi_models
    ["Pi 2 Model B v1.1", "Pi 2 Model B v1.2", "Pi Zero v1.2", "Pi Zero v1.3",
      "Pi Zero W", "Pi 3 Model B", "Pi 3 Model B+", "Pi 4"]
  end
end

app/views/rpis/_rpi.html.erb
<tr>
    <td class="text-left">
    <% if admin_priv? %>
    <%= link_to(delete_icon, rpi, method: :delete, data: { confirm: "You sure?" }) %>
    <% end %>
  </td>
  <td class="text-center">
    <%= link_to("#{rpi.rpi_name}", rpi) %>
  </td>
  <td width="20px">
  </td>

</tr>

app/views/rpis/edit.html.erb
<% provide(:title, "Update RPI") %>
<div class="row content-justify-center">
  <div class="col-sm-3">
  </div>
  <div class="col-md-5 shadow p-3 mb-5 bg-white rounded">
    <div class="card text-center">
      <div class="card-header text-white bg-primary text-center">
        <h4>Update Device</h4>
      </div>
      <div class="card-body text-center">
        <%= form_for(@rpi) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <table class="card-table table">
          <tr>
            <td class="text-left">
              <%= f.label :rpi_name, "Raspberry Pi Name"%>
              <%= f.text_field :rpi_name, class: 'form-control' %>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :rpi_location, "Raspberry Pi Location"%>
              <%= f.text_field :rpi_location, class: 'form-control' %>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :rpi_ip, "Raspberry Pi IP Address"%>
              <%= f.text_field :rpi_ip, class: 'form-control' %>
            </td>
          </tr>
        </table>
        <br><br>
        <%= f.submit "Update RPI", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>

app/views/rpis/index.html.erb
<% provide(:title, "Pi's") %>
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-md-5 shadow p-3 mb-5 bg-white rounded">
    <div class="card text-center">
      <div class="card-header text-white bg-primary text-center">
        <h4><%= link_to(add_icon, new_rpi_path) %>&nbsp;&nbsp;Raspberry Pi's</h4>
      </div>
      <div class="card-body text-center">
        <table class="card-table table">
          <%= will_paginate %>
          <%= render @rpis %>
          <%= will_paginate %>
        </table>
      </div>
      <div class="col-sm">
      </div>
    </div>
  </div>
</div>
<div class="row content-justify-center">
  <div class="col-sm">
  <br><br><br><br>
  </div>
</div>

app/views/rpis/new.html.erb
<% provide(:title, "Add RPI") %>
<div class="row content-justify-center">
  <div class="col-sm-3">
  </div>
  <div class="col-md-5 shadow p-3 mb-5 bg-white rounded">
    <div class="card text-center">
      <div class="card-header text-white bg-primary text-center">
        <h4>Add Raspberry Pi</h4>
      </div>
      <div class="card-body text-center">
        <%= simple_form_for(@rpi, html: { class: 'form-inline' }) do |f| %>
        <table class="card-table table">
          <tr>
            <td class="text-left">
              <%= render 'shared/error_messages', object: f.object %>
              <%= f.label :rpi_name, "Name", style: 'display: block;'%>
              <%= f.input :rpi_name, label: false, error: 'Name Required' %>
            </td>
          </tr>
          <tr>
            <td class="text-left">
              <%= f.label :rpi_model, "Model", style: 'display: block;'%>
              <%= f.input :rpi_model, label: false, collection: rpi_models,
                :prompt => true %>
            </td>
          </tr>
          <tr>
            <td class="text-left">
               <%= f.label :rpi_location, "Location", style: 'display: block;'%>
              <%= f.input :rpi_location, label: false %>
            </td>
          </tr>
          <tr>
            <td class="text-left">
               <%= f.label :rpi_ip, "IP Address", style: 'display: block;'%>
              <%= f.input :rpi_ip, label: false, error: 'IP Address Required' %>
            </td>
          </tr>
        </table>
        <br><br>
        <%= f.submit "Add RPI", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>

app/views/rpis/show.html.erb
<% provide(:title, @rpi.rpi_name) %>
<div class="d-flex justify-content-center">
  <div class="card shadow p-3 mb-5 bg-white rounded">
    <div class="card-header text-center text-white bg-primary">
      <div class="flex-column content-justify-center">
        <h4 align="center">
          <%= link_to(edit_icon, edit_rpi_path) %>
          &nbsp;&nbsp;
          <%= @rpi.rpi_name %>
        </h4>
      </div>
    </div>
    <div class="card-body text-center">
      <div class="d-md-flex">
        <table class="card-table table">
          <div class="d-flex flex-row">
            <tr>
              <th class="text-right">
                Location:
              </th>
              <td width="20px">
              </td>
              <td class="text-left">
                <%= @rpi.rpi_location %>
              </td>
            </tr>
            <tr>
              <th class="text-right">
                IP Address:
              </th>
              <td width="20px">
              </td>
              <td class="text-left">
                <%= @rpi.rpi_ip %>
              </td>
            </tr>
            <tr>
              <th class="text-right">
                Version:
              </th>
              <td width="20px">
              </td>
              <td class="text-left">
                <%= @rpi.rpi_model %>
              </td>
            </tr>
          </div>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="card shadow p-3 mb-5 bg-white rounded">
  <div class="card-header text-center text-white bg-primary">
    <h4>
      <%= link_to(add_icon, new_device_path(:rpis => @rpi.id)) %>
      &nbsp;&nbsp;
      <%= @rpi.rpi_name %> Devices
    </h4>
  </div>
  <div class="card-body text-center">
    <div class="d-lg-flex">
      <table width="100%" class="table table-striped">
       <div class="d-flex flex-row">
        <thead class="thead-light">
          <tr>
            <th scope="col">
              Action
            </th>
            <th scope="col">
              Name
            </th>
            <th scope="col">
              Location
            </th>
            <th scope="col">
              Input Type
            </th>
            <th scope="col">
              Pin Count
            </th>
            <th scope="col">
              Pin 1
            </th>
            <th scope="col">
              Pin 2
            </th>
            <th scope="col">
              Pin 3
           </th>
            <th scope="col">
              Pin 4
            </th>
            <th scope="col">
              Pin 5
            </th>
            <th scope="col">
              Data Recorded?
            </th>
          </tr>
      </thead>
      </div>
      <div class="d-flex flex-row">
        <% @devices.order(:dev_name).each  do |dev| %>
        <tr>
          <td>
            <%= link_to(delete_icon, device_path(dev.id), method: :delete, data: { confirm: "You sure?" }) %>&nbsp;
            <%= link_to(edit_icon, edit_device_path(:id => dev.id, :rpis => @rpi.id)) %>
          </td>
          <td>
            <%= dev.dev_name %>
          </td>
          <td>
            <%= dev.dev_location %>
          </td>
          <td>
            <%= dev.dev_input_signal %>
          </td>
          <td>
            <%= dev.dev_pin_count %>
          </td>
          <td>
            <%= dev.dev_pin1 %>
          </td>
          <td>
            <%= dev.dev_pin2 %>
          </td>
          <td>
            <%= dev.dev_pin3 %>
          </td>
          <td>
            <%= dev.dev_pin4 %>
          </td>
          <td>
            <%= dev.dev_pin5 %>
          </td>
          <td>
            <%= dev.dev_data %>
          </td>
        </tr>
        <% end %>
      </div>
    </table>
    </div>
  </div>
</div>